# Generated by Django 2.2.14 on 2021-07-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='amount_paid',
        ),
    ]
