# Generated by Django 2.2.14 on 2021-07-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='expenditure_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='received_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
