# Generated by Django 2.2.14 on 2021-07-22 03:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_auto_20210722_0316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Expenditure',
        ),
    ]
