# Generated by Django 2.2.14 on 2021-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210722_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
