# Generated by Django 2.2.14 on 2021-07-24 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_cash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='amount',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='cash',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.Cash')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
