# Generated by Django 2.2.14 on 2021-07-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='hisotry_type',
            new_name='history_type',
        ),
    ]
